<#

.Synopsis
Filename:     Install-Printer.ps1
Generated by: printDeploy

Installs the "{{DRIVER_NAME}}" driver and creates the "{{PRINTER_NAME}}" printer.
Required files must be in the same directory as this script when packaged as an Intune Win32 app.

Detection:

Rule Type:          Registry
Key path:           HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Print\Printers\{{PRINTER_NAME}}
Value:              Name
Detection method:   String comparison
Operator:           Equals
Name:               {{PRINTER_NAME}}

#>

$drivername = "{{DRIVER_NAME}}"

$portName = "{{PORT_NAME}}"
$PortAddress = "{{IP_ADDRESS}}"

# Staging Drivers
pnputil.exe /add-driver "$PSScriptRoot\{{INF_FILENAME}}" /install

# Restart the print spooler so it picks up the newly staged driver package;
# Add-PrinterDriver can otherwise fail right after staging with "driver not
# present in the driver store" because its driver list cache is stale.
Restart-Service -Name Spooler -Force

# Installing Drivers
Add-PrinterDriver -Name $drivername

# Install Printerport | Check if the port already exists
$checkPortExists = Get-PrinterPort -Name $portName -ErrorAction SilentlyContinue
if (-not $checkPortExists)
{
Add-PrinterPort -Name $portName -PrinterHostAddress $PortAddress
}

# Check if Printer Driver Exists
$printDriverExists = Get-PrinterDriver -Name $drivername -ErrorAction SilentlyContinue

# Install Printer
if ($printDriverExists)
{
Add-Printer -Name "{{PRINTER_NAME}}" -PortName $portName -DriverName $drivername
}
else
{
Write-Warning "Printer Driver not installed"
}

SLEEP 60
