<#

.Synopsis
Filename:     Remove-Printer.ps1
Generated by: printDeploy

Removes the "{{PRINTER_NAME}}" printer, its port and the "{{DRIVER_NAME}}" driver.

#>

Remove-Printer -Name "{{PRINTER_NAME}}"
SLEEP 60
Remove-PrinterPort -Name "{{PORT_NAME}}"
Remove-PrinterDriver -Name "{{DRIVER_NAME}}"
